export enum CategoryType {
  USERNAME = 'USERNAME',
  DOB = 'DOB',
  PERSONALITY_COMMUNICATION = 'PERSONALITY_COMMUNICATION',
  INTRODUCTION = 'INTRODUCTION',
  CONCLUSION = 'CONCLUSION',
  VALUES_RELATIONSHIP_ATTITUDES = 'VALUES_RELATIONSHIP_ATTITUDES',
  IDENTITY_RELATIONSHIP_INTENTIONS = 'IDENTITY_RELATIONSHIP_INTENTIONS',
  LIFESTYLE_HABITS = 'LIFESTYLE_HABITS',
  GENDER = 'GENDER',
} 