export enum QuestionType {
  SINGLE_CHOICE = 'SINGLE_CHOICE',

  MULTIPLE_CHOICE = 'MULTIPLE_CHOICE',

  TEXT_INPUT = 'TEXT_INPUT',

  NUMBER_INPUT = 'NUMBER_INPUT',

  DATE_INPUT = 'DATE_INPUT',

  AUTOCOMPLETE_INPUT = 'AUTOCOMPLETE_INPUT',

  COUNTRY_SELECTION = 'COUNTRY_SELECTION',

  JOB_SELECTION = 'JOB_SELECTION',

  ONE_TO_FIVE = 'ONE_TO_FIVE',
}
