version: '3.9'
name: singlesmeetup2
services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.3
    command:
      - start-dev
      - --http-port=9090
      - --hostname=auth.gotrumeet.com
      - --proxy-headers=xforwarded
      - --hostname-strict=false
      - --import-realm
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./realm-config/keycloak-health-check.sh:/opt/keycloak/health-check.sh
    environment:
      - KC_DB=dev-file
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_FEATURES=scripts
      - KC_HEALTH_ENABLED=true
      - KC_HTTP_PORT=9090
      - KC_HOSTNAME=auth.gotrumeet.com
      - KC_HOSTNAME_STRICT=false
      - KC_PROXY_HEADERS=xforwarded
      - KC_PROXY_TRUSTED_ADDRESSES=0.0.0.0/0,::/0
      # Removed KC_PROXY_PROTOCOL_ENABLED to avoid conflict
    ports:
      - "9090:9090"
    healthcheck:
      test: 'bash /opt/keycloak/health-check.sh'
      interval: 5s
      timeout: 5s
      retries: 50
      start_period: 10s
    restart: unless-stopped
