# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: singlesmeetup2
services:
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql
  keycloak:
    extends:
      file: ./keycloak.yml
      service: keycloak
