export const JOBS = [
  // Technology & IT
  'Software Engineer',
  'Software Developer',
  'Web Developer',
  'Mobile App Developer',
  'Full Stack Developer',
  'Frontend Developer',
  'Backend Developer',
  'DevOps Engineer',
  'Data Scientist',
  'Data Analyst',
  'Database Administrator',
  'System Administrator',
  'Network Administrator',
  'Cybersecurity Specialist',
  'IT Support Specialist',
  'Product Manager',
  'Project Manager',
  'UX/UI Designer',
  'Graphic Designer',
  'Quality Assurance Engineer',
  'Machine Learning Engineer',
  'Cloud Architect',
  'Technical Writer',
  
  // Healthcare & Medical
  'Doctor',
  'Nurse',
  'Dentist',
  'Pharmacist',
  'Physical Therapist',
  'Psychologist',
  'Psychiatrist',
  'Veterinarian',
  'Medical Assistant',
  'Radiologist',
  'Surgeon',
  'Pediatrician',
  'Cardiologist',
  'Dermatologist',
  'Optometrist',
  'Chiropractor',
  'Medical Researcher',
  
  // Business & Finance
  'Accountant',
  'Financial Advisor',
  'Investment Banker',
  'Business Analyst',
  'Management Consultant',
  'Marketing Manager',
  'Sales Manager',
  'Human Resources Manager',
  'Operations Manager',
  'Chief Executive Officer',
  'Chief Financial Officer',
  'Chief Technology Officer',
  'Entrepreneur',
  'Real Estate Agent',
  'Insurance Agent',
  'Tax Advisor',
  'Auditor',
  'Financial Planner',
  'Business Development Manager',
  'Customer Success Manager',
  
  // Education & Research
  'Teacher',
  'Professor',
  'Principal',
  'School Counselor',
  'Librarian',
  'Research Scientist',
  'Academic Researcher',
  'Tutor',
  'Educational Administrator',
  'Curriculum Developer',
  'Training Specialist',
  
  // Creative & Media
  'Artist',
  'Photographer',
  'Videographer',
  'Writer',
  'Journalist',
  'Editor',
  'Content Creator',
  'Social Media Manager',
  'Marketing Specialist',
  'Public Relations Specialist',
  'Advertising Executive',
  'Film Director',
  'Actor',
  'Musician',
  'Interior Designer',
  'Fashion Designer',
  'Architect',
  'Animator',
  'Game Designer',
  
  // Legal & Government
  'Lawyer',
  'Attorney',
  'Judge',
  'Paralegal',
  'Legal Assistant',
  'Police Officer',
  'Detective',
  'Firefighter',
  'Government Official',
  'Policy Analyst',
  'Social Worker',
  'Probation Officer',
  
  // Engineering & Manufacturing
  'Mechanical Engineer',
  'Electrical Engineer',
  'Civil Engineer',
  'Chemical Engineer',
  'Aerospace Engineer',
  'Industrial Engineer',
  'Environmental Engineer',
  'Biomedical Engineer',
  'Manufacturing Engineer',
  'Quality Control Inspector',
  'Production Manager',
  'Plant Manager',
  'Maintenance Technician',
  
  // Sales & Customer Service
  'Sales Representative',
  'Account Manager',
  'Customer Service Representative',
  'Retail Manager',
  'Store Manager',
  'Cashier',
  'Sales Associate',
  'Call Center Agent',
  'Technical Support Specialist',
  
  // Hospitality & Tourism
  'Hotel Manager',
  'Restaurant Manager',
  'Chef',
  'Cook',
  'Waiter/Waitress',
  'Bartender',
  'Travel Agent',
  'Tour Guide',
  'Event Planner',
  'Wedding Planner',
  'Concierge',
  
  // Transportation & Logistics
  'Pilot',
  'Flight Attendant',
  'Truck Driver',
  'Delivery Driver',
  'Logistics Coordinator',
  'Supply Chain Manager',
  'Warehouse Manager',
  'Shipping Clerk',
  'Air Traffic Controller',
  
  // Skilled Trades
  'Electrician',
  'Plumber',
  'Carpenter',
  'Mechanic',
  'HVAC Technician',
  'Welder',
  'Painter',
  'Roofer',
  'Landscaper',
  'Construction Worker',
  'Contractor',
  
  // Sports & Fitness
  'Personal Trainer',
  'Fitness Instructor',
  'Sports Coach',
  'Athletic Trainer',
  'Professional Athlete',
  'Sports Analyst',
  'Gym Manager',
  'Nutritionist',
  'Dietitian',
  
  // Other Professional Services
  'Consultant',
  'Freelancer',
  'Contractor',
  'Self-Employed',
  'Retired',
  'Student',
  'Unemployed',
  'Stay-at-Home Parent',
  'Volunteer',
  'Non-Profit Worker',
  'Community Organizer',
  'Life Coach',
  'Career Counselor',
  'Translator',
  'Interpreter'
]; 